# Generated by Django 3.2.9 on 2022-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20220312_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
