# Generated by Django 3.2.9 on 2022-03-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20220312_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdFundingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=10)),
                ('starttime', models.CharField(max_length=10)),
                ('location', models.TextField(max_length=1000)),
                ('type1', models.TextField(max_length=1000)),
                ('desc', models.TextField(max_length=1000)),
                ('endtime', models.CharField(max_length=10)),
                ('reqdamt', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='deadline',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='reqdppl',
            field=models.CharField(default='', max_length=255),
        ),
    ]
