# Generated by Django 3.2.9 on 2022-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20220312_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfundingdetails',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='date',
            field=models.DateField(),
        ),
    ]
